package ru.splitus.error;

public enum ApiErrorCode {
    VALIDATION_ERROR,
    AUTHENTICATION_FAILED,
    CHECK_NOT_FOUND,
    PARTICIPANT_NOT_FOUND,
    PARTICIPANT_DOES_NOT_BELONG_TO_CHECK,
    PARTICIPANT_NAME_CONFLICT,
    PARTICIPANT_LIMIT_REACHED,
    CHECK_CREATION_LIMIT_REACHED,
    REGISTERED_PARTICIPANT_ALREADY_EXISTS,
    PARTICIPANT_MERGE_INVALID,
    EXPENSE_NOT_FOUND,
    EXPENSE_SPLIT_REQUIRED,
    EXPENSE_AMOUNT_INVALID,
    EXPENSE_AUTHOR_MISMATCH,
    SETTLEMENT_ALREADY_RUNNING,
    SETTLEMENT_STATE_CHANGED
}
