package ru.splitus.error;

public enum ApiErrorCode {
    VALIDATION_ERROR,
    AUTHENTICATION_FAILED,
    CHECK_NOT_FOUND,
    PARTICIPANT_NOT_FOUND,
    PARTICIPANT_NAME_CONFLICT,
    PARTICIPANT_LIMIT_REACHED,
    CHECK_CREATION_LIMIT_REACHED,
    REGISTERED_PARTICIPANT_ALREADY_EXISTS
}

